site_name: NDN 101
theme:
  name: material
  palette:
    primary: pink

nav:
  - 'index.md'
  - 'getting-started.md'
  - 'packets.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format