site_name: NDN 101
repo_url: https://github.com/pulsejet/ndn101-md

theme:
  name: material
  icon:
    logo: material/network
  favicon: img/ndn.png
  palette:
    primary: deep orange
  features:
  - content.tabs.link
  - navigation.footer
  - content.code.copy

plugins:
  - search
  - bibtex:
      bib_file: ndn.bib
      bib_by_default: true
      csl_file: acm-sig-proceedings.csl

nav:
  - 'index.md'
  - 'getting-started.md'
  - 'packets.md'
  - 'communication.md'
  - 'forwarding.md'
  - 'security.md'
  - 'sync.md'
  - 'routing.md'
  - 'testbed.md'
  - 'debugging.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/iframe-message.js