site_name: NDN 101
theme:
  name: material
  icon:
    logo: material/web
  favicon: /ndn.png
  palette:
    primary: deep orange
  features:
  - content.tabs.link
  - navigation.footer

nav:
  - 'index.md'
  - 'getting-started.md'
  - 'packets.md'
  - 'communication.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true